---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ritalic

<!-- badges: start -->
<!-- badges: end -->

**ritalic** is an R package which gives you access to [ITALIC](https://italic.units.it/) mediated data via its [REST API](https://italic.units.it/index.php?procedure=api). 

**ITALIC** the Information System on Italian Lichens, makes available information and resources about the lichens known to occur in Italy. It is maintained and updated by the Research Unit of Professor Pier Luigi Nimis, at the University of Trieste (NE Italy), Department of Life Sciences. Most of the data are derived from the Checklist of the Lichens of Italy by Nimis (2016), but nomenclatural and distributional data are being continuously updated online, and complete identification keys for some areas of the country, as well as for genera or groups of genera, are published online for testing.


## Installation

You can install the development version of ritalic from [GitHub](https://github.com/Mattciao96/ritalic) with:

``` r
# install.packages("devtools")
devtools::install_github("Mattciao96/ritalic")
```



